spring:
  application:
    name: springai1

  http:
    clients:
      connect-timeout: 5s
      read-timeout: 10m

  ai:
    retry:
      max-attempts: 1

    ollama:
      base-url: http://localhost:11434

      chat:
        model: qwen3:4b-instruct
        num-predict: 256
        temperature: 0.2
        think: false
